name: Check and Test the source code
on:
 pull_request:
  branches:
   - main
jobs:
 test:
  runs-on: ubuntu-latest
  steps:
   - uses: actions/checkout@v3
   - uses: subosito/flutter-action@v2.3.0
     with:
      flutter-version: '3.7.8'
   - name: Install packages
     run: flutter pub get
   - name: Linter
     run: flutter analyze
   - name: Unit Test
     run: flutter test