name: Integration Test

on:
  pull_request:
    branches:
      - main
jobs:
  test:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v4
      - uses: futureware-tech/simulator-action@v3
        with:
          model: 'iPhone 14'
      - uses: subosito/flutter-action@v2.3.0
        with:
          flutter-version: '3.7.8'
      - run: flutter pub get
      - run: flutter test integration_test